# Generated by Django 5.0.3 on 2024-03-18 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Member',
            new_name='Employee',
        ),
    ]
